### ISSUE TITLE
Exception in Client

### ISSUE THREAD

**Issue by abentele** [jo-source/jo-client-platform#21]
mir ist gerade eine Exception im Client aufgefallen:

```
Exception in thread "pool-1-thread-14" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at java.util.AbstractCollection.toArray(Unknown Source)
	at java.util.LinkedList.addAll(Unknown Source)
	at java.util.LinkedList.addAll(Unknown Source)
	at java.util.LinkedList.<init>(Unknown Source)
	at org.jowidgets.cap.ui.impl.ExecutionTask.fireFinished(ExecutionTask.java:283)
	at org.jowidgets.cap.ui.impl.ExecutionTask.finshed(ExecutionTask.java:113)
	at org.jowidgets.cap.remoting.client.InvocationCallback.finished(InvocationCallback.java:77)
	at org.jowidgets.invocation.service.client.impl.InvocationCallbackServiceImpl.finished(InvocationCallbackServiceImpl.java:82)
	at org.jowidgets.invocation.client.impl.InvocationClientServiceRegistryImpl.onFinished(InvocationClientServiceRegistryImpl.java:61)
	at org.jowidgets.invocation.client.impl.InvocationCallbackMessageReceiver.onMessage(InvocationCallbackMessageReceiver.java:60)
	at org.jowidgets.message.impl.http.client.MessageBroker$3.run(MessageBroker.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Ich habe zuvor in der Applikation mehrere Datensätze auf einmal gelöscht.

Mir fällt auf, dass Zugriffe auf die Variable org.jowidgets.cap.ui.impl.ExecutionTask.executionTaskListeners nicht synchronisiert sind. Vermutlich müsste das synchronisiert sein.

**Comment by herrgrossmann** [comment]
Der Commit https://github.com/jo-source/jo-client-platform/commit/04d381a8620781fe94c9a9c9b9769f728404366d  hat den Fehler behoben. Der Bugfix ist ab jo-client-platform Version 0.50.0 verfügbar.
