### ISSUE TITLE
Error log entries when service invocation was canceled

### ISSUE THREAD

**Issue by herrgrossmann** [jo-source/jo-client-platform#76]
When a service invocation was canceled by user, sometimes there are logentries with ERROR loglevel.

This entries should not occure because cancel is a default use case and no exception.

2017-10-11 09:46:33,617 ERROR org.jowidgets.message.api.MessageToolkit.handleExceptions     - Error on message broker 'org.jowidgets.cap.remoting.common.RemotingBrokerId_DEFAULT_REMOTING_BROKER_ID'
java.lang.IllegalStateException: No message channel is registered for invocationId '998258b8-7e05-4558-bdf5-60f591f1850a'
	at org.jowidgets.invocation.server.impl.InvocationServerImpl$2.send(InvocationServerImpl.java:116) [org.jowidgets.invocation.server.impl-0.65.0.jar:na]
	at org.jowidgets.invocation.server.impl.InvocationServerImpl$1.exeption(InvocationServerImpl.java:77) [org.jowidgets.invocation.server.impl-0.65.0.jar:na]
	at org.jowidgets.invocation.service.server.impl.MethodImpl$1.exeption(MethodImpl.java:82) [org.jowidgets.invocation.service.server.impl-0.65.0.jar:na]
	at org.jowidgets.cap.remoting.server.ServerResultCallback.exception(ServerResultCallback.java:49) [org.jowidgets.cap.remoting.server-0.65.0.jar:na]
	at org.jowidgets.cap.service.jpa.impl.JpaServicesDecoratorProviderImpl$JpaInvocationHandler$DecoratedResultCallback.exception(JpaServicesDecoratorProviderImpl.java:345) [org.jowidgets.cap.service.jpa.impl-0.65.0.jar:na]
	at org.jowidgets.cap.service.hibernate.impl.CancelServicesDecoratorProviderImpl$CancelableInvoker$DecoratedResultCallback.exception(CancelServicesDecoratorProviderImpl.java:257) [org.jowidgets.cap.service.hibernate-0.65.0.jar:na]
	at org.jowidgets.cap.service.impl.ReaderServiceAdapter.read(ReaderServiceAdapter.java:73) [org.jowidgets.cap.service-0.65.0.jar:na]
	at sun.reflect.GeneratedMethodAccessor374.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
	at org.jowidgets.cap.security.service.impl.SecureServiceDecoratorProviderImpl$SecurityInvocationHandler.invoke(SecureServiceDecoratorProviderImpl.java:108) [org.jowidgets.cap.security.service-0.65.0.jar:na]
	at com.sun.proxy.$Proxy790.read(Unknown Source) [na:na]
	at sun.reflect.GeneratedMethodAccessor374.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
	at org.jowidgets.cap.service.hibernate.impl.CancelServicesDecoratorProviderImpl$CancelableInvoker.invoke(CancelServicesDecoratorProviderImpl.java:179) [org.jowidgets.cap.service.hibernate-0.65.0.jar:na]
	at org.jowidgets.cap.service.hibernate.impl.CancelServicesDecoratorProviderImpl$CancelableInvoker.access$300(CancelServicesDecoratorProviderImpl.java:140) [org.jowidgets.cap.service.hibernate-0.65.0.jar:na]
	at org.jowidgets.cap.service.hibernate.impl.CancelServicesDecoratorProviderImpl$CancelInvocationHandler.invokeAsyncSignature(CancelServicesDecoratorProviderImpl.java:135) [org.jowidgets.cap.service.hibernate-0.65.0.jar:na]
	at org.jowidgets.cap.common.tools.proxy.AbstractCapServiceInvocationHandler.invoke(AbstractCapServiceInvocationHandler.java:60) [org.jowidgets.cap.common-0.65.0.jar:na]
	at com.sun.proxy.$Proxy790.read(Unknown Source) [na:na]
	at sun.reflect.GeneratedMethodAccessor374.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
	at org.jowidgets.cap.service.jpa.impl.JpaServicesDecoratorProviderImpl$JpaInvocationHandler.invokeAsyncSignature(JpaServicesDecoratorProviderImpl.java:199) [org.jowidgets.cap.service.jpa.impl-0.65.0.jar:na]
	at org.jowidgets.cap.common.tools.proxy.AbstractCapServiceInvocationHandler.invoke(AbstractCapServiceInvocationHandler.java:60) [org.jowidgets.cap.common-0.65.0.jar:na]
	at com.sun.proxy.$Proxy790.read(Unknown Source) [na:na]
	at sun.reflect.GeneratedMethodAccessor376.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
	at org.jowidgets.cap.remoting.server.GenericRemoteMethod.invokeMethodOnService(GenericRemoteMethod.java:173) [org.jowidgets.cap.remoting.server-0.65.0.jar:na]
	at org.jowidgets.cap.remoting.server.GenericRemoteMethod.invoke(GenericRemoteMethod.java:68) [org.jowidgets.cap.remoting.server-0.65.0.jar:na]
	at org.jowidgets.cap.remoting.server.GenericRemoteMethod.invoke(GenericRemoteMethod.java:47) [org.jowidgets.cap.remoting.server-0.65.0.jar:na]
	at org.jowidgets.invocation.service.server.impl.MethodImpl.invoke(MethodImpl.java:104) [org.jowidgets.invocation.service.server.impl-0.65.0.jar:na]
	at org.jowidgets.invocation.server.impl.InvocationServerServiceRegistryImpl.onMethodInvocation(InvocationServerServiceRegistryImpl.java:75) [org.jowidgets.invocation.server.impl-0.65.0.jar:na]
	at org.jowidgets.invocation.server.impl.InvocationServerMessageReceiver.onMessage(InvocationServerMessageReceiver.java:69) [org.jowidgets.invocation.server.impl-0.65.0.jar:na]
	at org.jowidgets.message.impl.http.server.Connection.doRun(Connection.java:75) [org.jowidgets.message.impl.http.server-0.65.0.jar:na]
	at org.jowidgets.message.impl.http.server.Connection.doRun(Connection.java:80) [org.jowidgets.message.impl.http.server-0.65.0.jar:na]
	at org.jowidgets.message.impl.http.server.Connection.doRun(Connection.java:80) [org.jowidgets.message.impl.http.server-0.65.0.jar:na]
	at org.jowidgets.message.impl.http.server.Connection.access$000(Connection.java:44) [org.jowidgets.message.impl.http.server-0.65.0.jar:na]
	at org.jowidgets.message.impl.http.server.Connection$1.run(Connection.java:65) [org.jowidgets.message.impl.http.server-0.65.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: org.jowidgets.cap.common.api.exception.ServiceCanceledException: Service was canceled by user
	... 38 common frames omitted

**Comment by herrgrossmann** [comment]
Will be available with version 0.72.0
