### ISSUE TITLE
StreamCorruptedException in MessageBroker on status code 500

### ISSUE THREAD

**Issue by herrgrossmann** [jo-source/jo-client-platform#79]
When MessageServler throws an internal server error (status code 500) an StreamCorruptedException will be thrown.

In this case the connection will not be consumed completely, so if this happens more than once no more messages can be received or send to server anymore, because http execution hangs until client will be restartet.

Reproduction:

- Use kitchensink sample 2, org.jowidgets.samples.kitchensink.sample2.app.service.security.SampleAuthenticationService
- Throw an exception for guest credentials
- Login a few times with guest credentials
- After a few attempts the StreamCorruptedException occures in client log
- If this has happend twice, no more messages will send to server or can be received because no more connections are available from connection pool

Fix:

Status line must be checked before ObjectInputStream will be created and entity must be completed in finally block

Remark: 

This inexpressive exception will also be thrown on client if client and server versions missmatch. After this will be fixed a better exception should be shown on client instead.

Exception stack trace:

java.io.StreamCorruptedException: invalid stream header: 3C68746D
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:781)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:278)
	at org.jowidgets.classloading.tools.SharedClassLoadingObjectInputStream.<init>(SharedClassLoadingObjectInputStream.java:42)
	at org.jowidgets.message.impl.http.client.MessageBroker.receiveMessages(MessageBroker.java:215)
	at org.jowidgets.message.impl.http.client.MessageBroker.access$1(MessageBroker.java:201)
	at org.jowidgets.message.impl.http.client.MessageBroker$2.run(MessageBroker.java:194)
	at java.lang.Thread.run(Thread.java:662)

Stack trace of sender thread when no more connections are available:

"org.jowidgets.message.impl.http.client.MessageBroker-messageSender" daemon prio=6 tid=0x000000000cc80800 nid=0x3340 waiting on condition [0x000000000d75f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006b6dbe408> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
	at org.apache.http.impl.conn.tsccm.WaitingThread.await(WaitingThread.java:158)
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking(ConnPoolByRoute.java:403)
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry(ConnPoolByRoute.java:300)
	at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection(ThreadSafeClientConnManager.java:224)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:391)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at org.jowidgets.message.impl.http.client.MessageBroker.sendMessages(MessageBroker.java:143)
	at org.jowidgets.message.impl.http.client.MessageBroker.access$0(MessageBroker.java:130)
	at org.jowidgets.message.impl.http.client.MessageBroker$1.run(MessageBroker.java:123)
	at java.lang.Thread.run(Thread.java:662)

Stack trace of receiver thread when no more connections are available:

"org.jowidgets.message.impl.http.client.MessageBroker-messageReceiver" daemon prio=6 tid=0x000000000cc67000 nid=0x20ec waiting on condition [0x000000000e8cf000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006b6157c70> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
	at org.apache.http.impl.conn.tsccm.WaitingThread.await(WaitingThread.java:158)
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking(ConnPoolByRoute.java:403)
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry(ConnPoolByRoute.java:300)
	at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection(ThreadSafeClientConnManager.java:224)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:391)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at org.jowidgets.message.impl.http.client.MessageBroker.receiveMessages(MessageBroker.java:210)
	at org.jowidgets.message.impl.http.client.MessageBroker.access$1(MessageBroker.java:201)
	at org.jowidgets.message.impl.http.client.MessageBroker$2.run(MessageBroker.java:194)
	at java.lang.Thread.run(Thread.java:662)

**Comment by herrgrossmann** [comment]
Fixed since 0.71.0 (and on maintenance branch 0.65 since 0.65.2)

**Comment by herrgrossmann** [comment]
Will be available with version 0.72.0
